// types/UIStates.ts
export enum UIStates {
  CHOOSING_GRAVITY,
  WAITING_FOR_START_POINT,
  WAITING_FOR_END_POINT,
  CHOOSING_CURVE,
  INSERTING_INTERMEDIATE_POINTS,
  CHOOSING_CONVEXITY,
  CHOOSING_RADIUS,
  CHOOSING_MASS,
  READY_TO_SIMULATE,
  SIMULATING,
  SHOWING_RESULTS,
}
